### ISSUE TITLE
How we can use this for image feature?

### ISSUE THREAD

**Issue by vinodkkurmi** [rpryzant/proxy-a-distance#1]
Hi, how we can extend this code to use for image feature(where we don't have any vocab)?
Can you provide that script?

Thank you

**Comment by rpryzant** [comment]
Image data isn't supported. Sorry! 

If you wanted to use image data with this package, I suppose you could implement a new Dataset object with the same interface as (https://github.com/rpryzant/proxy-a-distance/blob/master/src/dataset.py). 

Otherwise I'd recommend just doing it yourself: build a classifier to distinguish your domains and then measure it's error rate.
