### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yleniarotalinti** [rpryzant/proxy-a-distance#2]
Hi, 
thank you for this piece of code. 

I do have a question: the value of the metric is always negative, isn't it?
If PAD=-3 the distributions are more similar than the situation where PAD=-1. Am I correct?

Thank you in advance,
Ylenia

**Comment by rpryzant** [comment]
So intuitively, 

Similar domains => smaller error => bigger PAD

Dissimilar domains => bigger error => smaller PAD

For your example an error of 0.75 would lead to PAD of -1 and error of 1.25 would lead to PAD of -3. The -1 PAD implies more similarity because of the reduced error. 

Sorry this isn't explained clearly in the README, I've updated it and should hopefully be clearer now.

**Comment by yleniarotalinti** [comment]
got it!

Thank you very much!

Il giorno gio 21 lug 2022 alle ore 15:41 Reid Pryzant <
***@***.***> ha scritto:

**Comment by mklimasz** [comment]
Hi,
I might be wrong @rpryzant, but I think the README change is not correct.

Similar domains means bigger error as a classifier cannot (or has problems to) distinguish domains and therefore PAD is lower.

```
Similar domains => **bigger** error => **smaller** PAD

Dissimilar domains => **smaller** error => **bigger** PAD
```

Also unless the MAE/binary classification problem was changed, the error shouldn't exceed $[0, 1]$ (in practice $[0, 0.5]$),
so the value of the PAD metric (in practice) should be in range $[0, 2]$.

**Comment by rpryzant** [comment]
Thanks! Yes you're totally right, so sorry for the confusion. I've updated the README accordingly. Feel free to submit a PR if you'd like to improve further.
